version: "3.6"
services:
  techbuzz-db:
    image: postgres:15.1-alpine
    container_name: techbuzz-db
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog
    platform: linux/x86_64
    ports:
      - "1025:1025"
      - "8025:8025"
    profiles:
      - local
